CREATE TABLE BOARDALL(
        BOARDSEQ NUMBER(8) PRIMARY KEY,
        ID VARCHAR2(50) NOT NULL, 
        BOARDTYPE NUMBER(2) NOT NULL,
        TITLE VARCHAR2(200) NOT NULL,
        CONTENT VARCHAR2(4000) NOT NULL,
        READCOUNT NUMBER(8) NOT NULL,
        COMMENTCOUNT NUMBER(8) NOT NULL,
        
        WDATE DATE NOT NULL,
        DEL NUMBER(1) NOT NULL
    );

-- 제약조건 추가 (ID)
ALTER TABLE BOARDALL ADD CONSTRAINT FK_BOARDALL
      FOREIGN KEY (IDQ)
      REFERENCES MEMBERMBTI(ID)
      ON DELETE SET NULL;
    
CREATE SEQUENCE BOARDSEQ
START WITH 1 INCREMENT BY 1;

-- food
INSERT INTO BOARDALL(BOARDSEQ,ID,BOARDTYPE,TITLE,CONTENT,READCOUNT,COMMENTCOUNT,WDATE,DEL)
VALUES(BOARDSEQ.NEXTVAL, 'hsh', 17, 'porkBelly', '삼겹살',0,0,'22/01/13', 0);
INSERT INTO BOARDALL(BOARDSEQ,ID,BOARDTYPE,TITLE,CONTENT,READCOUNT,COMMENTCOUNT,WDATE,DEL)
VALUES(BOARDSEQ.NEXTVAL, 'hsh', 17, 'steak', '스테이크',0,0,'22/01/13', 0);
INSERT INTO BOARDALL(BOARDSEQ,ID,BOARDTYPE,TITLE,CONTENT,READCOUNT,COMMENTCOUNT,WDATE,DEL)
VALUES(BOARDSEQ.NEXTVAL, 'hsh', 17, 'tteokbokki', '떡볶이',0,0,'22/01/13', 0);
INSERT INTO BOARDALL(BOARDSEQ,ID,BOARDTYPE,TITLE,CONTENT,READCOUNT,COMMENTCOUNT,WDATE,DEL)
VALUES(BOARDSEQ.NEXTVAL, 'hsh', 17, 'chicken', '치킨',0,0,'22/01/13', 0);
INSERT INTO BOARDALL(BOARDSEQ,ID,BOARDTYPE,TITLE,CONTENT,READCOUNT,COMMENTCOUNT,WDATE,DEL)
VALUES(BOARDSEQ.NEXTVAL, 'hsh', 17, 'gookbab', '국밥',0,0,'22/01/13', 0);
INSERT INTO BOARDALL(BOARDSEQ,ID,BOARDTYPE,TITLE,CONTENT,READCOUNT,COMMENTCOUNT,WDATE,DEL)
VALUES(BOARDSEQ.NEXTVAL, 'hsh', 17, 'pasta', '파스타',0,0,'22/01/13', 0);
INSERT INTO BOARDALL(BOARDSEQ,ID,BOARDTYPE,TITLE,CONTENT,READCOUNT,COMMENTCOUNT,WDATE,DEL)
VALUES(BOARDSEQ.NEXTVAL, 'hsh', 17, 'pizza', '피자',0,0,'22/01/13', 0);
INSERT INTO BOARDALL(BOARDSEQ,ID,BOARDTYPE,TITLE,CONTENT,READCOUNT,COMMENTCOUNT,WDATE,DEL)
VALUES(BOARDSEQ.NEXTVAL, 'hsh', 17, 'sushi', '스시',0,0,'22/01/13', 0);

-- celebrity
INSERT INTO BOARDALL(BOARDSEQ,ID,BOARDTYPE,TITLE,CONTENT,READCOUNT,COMMENTCOUNT,WDATE,DEL)
VALUES(BOARDSEQ.NEXTVAL, 'hsh', 17, '강호동', '강호동',0,0,'22/01/19', 0);
INSERT INTO BOARDALL(BOARDSEQ,ID,BOARDTYPE,TITLE,CONTENT,READCOUNT,COMMENTCOUNT,WDATE,DEL)
VALUES(BOARDSEQ.NEXTVAL, 'hsh', 17, '김연아', '김연아',0,0,'22/01/19', 0);
INSERT INTO BOARDALL(BOARDSEQ,ID,BOARDTYPE,TITLE,CONTENT,READCOUNT,COMMENTCOUNT,WDATE,DEL)
VALUES(BOARDSEQ.NEXTVAL, 'hsh', 17, '민경훈', '민경훈',0,0,'22/01/19', 0);
INSERT INTO BOARDALL(BOARDSEQ,ID,BOARDTYPE,TITLE,CONTENT,READCOUNT,COMMENTCOUNT,WDATE,DEL)
VALUES(BOARDSEQ.NEXTVAL, 'hsh', 17, '웨렌버핏', '웨렌버핏',0,0,'22/01/19', 0);
INSERT INTO BOARDALL(BOARDSEQ,ID,BOARDTYPE,TITLE,CONTENT,READCOUNT,COMMENTCOUNT,WDATE,DEL)
VALUES(BOARDSEQ.NEXTVAL, 'hsh', 17, '유재석', '유재석',0,0,'22/01/19', 0);
INSERT INTO BOARDALL(BOARDSEQ,ID,BOARDTYPE,TITLE,CONTENT,READCOUNT,COMMENTCOUNT,WDATE,DEL)
VALUES(BOARDSEQ.NEXTVAL, 'hsh', 17, '윤하', '윤하',0,0,'22/01/19', 0);
INSERT INTO BOARDALL(BOARDSEQ,ID,BOARDTYPE,TITLE,CONTENT,READCOUNT,COMMENTCOUNT,WDATE,DEL)
VALUES(BOARDSEQ.NEXTVAL, 'hsh', 17, '이경규', '이경규',0,0,'22/01/19', 0);
INSERT INTO BOARDALL(BOARDSEQ,ID,BOARDTYPE,TITLE,CONTENT,READCOUNT,COMMENTCOUNT,WDATE,DEL)
VALUES(BOARDSEQ.NEXTVAL, 'hsh', 17, '태연', '태연',0,0,'22/01/19', 0);

-- color
INSERT INTO BOARDALL(BOARDSEQ,ID,BOARDTYPE,TITLE,CONTENT,READCOUNT,COMMENTCOUNT,WDATE,DEL)
VALUES(BOARDSEQ.NEXTVAL, 'hsh', 17, 'porkBelly', '삼겹살',0,0,'22/01/13', 0);
INSERT INTO BOARDALL(BOARDSEQ,ID,BOARDTYPE,TITLE,CONTENT,READCOUNT,COMMENTCOUNT,WDATE,DEL)
VALUES(BOARDSEQ.NEXTVAL, 'hsh', 17, 'steak', '스테이크',0,0,'22/01/13', 0);
INSERT INTO BOARDALL(BOARDSEQ,ID,BOARDTYPE,TITLE,CONTENT,READCOUNT,COMMENTCOUNT,WDATE,DEL)
VALUES(BOARDSEQ.NEXTVAL, 'hsh', 17, 'tteokbokki', '떡볶이',0,0,'22/01/13', 0);
INSERT INTO BOARDALL(BOARDSEQ,ID,BOARDTYPE,TITLE,CONTENT,READCOUNT,COMMENTCOUNT,WDATE,DEL)
VALUES(BOARDSEQ.NEXTVAL, 'hsh', 17, 'chicken', '치킨',0,0,'22/01/13', 0);
INSERT INTO BOARDALL(BOARDSEQ,ID,BOARDTYPE,TITLE,CONTENT,READCOUNT,COMMENTCOUNT,WDATE,DEL)
VALUES(BOARDSEQ.NEXTVAL, 'hsh', 17, 'gookbab', '국밥',0,0,'22/01/13', 0);
INSERT INTO BOARDALL(BOARDSEQ,ID,BOARDTYPE,TITLE,CONTENT,READCOUNT,COMMENTCOUNT,WDATE,DEL)
VALUES(BOARDSEQ.NEXTVAL, 'hsh', 17, 'pasta', '파스타',0,0,'22/01/13', 0);
INSERT INTO BOARDALL(BOARDSEQ,ID,BOARDTYPE,TITLE,CONTENT,READCOUNT,COMMENTCOUNT,WDATE,DEL)
VALUES(BOARDSEQ.NEXTVAL, 'hsh', 17, 'pizza', '피자',0,0,'22/01/13', 0);
INSERT INTO BOARDALL(BOARDSEQ,ID,BOARDTYPE,TITLE,CONTENT,READCOUNT,COMMENTCOUNT,WDATE,DEL)
VALUES(BOARDSEQ.NEXTVAL, 'hsh', 17, 'sushi', '스시',0,0,'22/01/13', 0);   

commit;
    
    
    
SELECT
    * FROM BOARDALL;
    
DROP TABLE BOARDALL CASCADE CONSTRAINTS;
DROP SEQUENCE BOARDSEQ;
