CREATE TABLE BOARDALL(
        BOARDSEQ NUMBER(8) PRIMARY KEY,
        ID VARCHAR2(50) NOT NULL, 
        BOARDTYPE NUMBER(2) NOT NULL,
        TITLE VARCHAR2(200) NOT NULL,
        CONTENT VARCHAR2(4000) NOT NULL,
        READCOUNT NUMBER(8) NOT NULL,
        COMMENTCOUNT NUMBER(8) NOT NULL,
        
        WDATE DATE NOT NULL,
        DEL NUMBER(1) NOT NULL
    );


    
CREATE SEQUENCE BOARDSEQ
START WITH 1 INCREMENT BY 1;

INSERT INTO BOARDALL(BOARDSEQ,ID,BOARDTYPE,TITLE,CONTENT,READCOUNT,COMMENTCOUNT,WDATE,DEL)
VALUES(BOARDSEQ.NEXTVAL, 'admin', 17, 'porkBelly', '»ï°ã»ì',0,0,'22/01/13', 0);
INSERT INTO BOARDALL(BOARDSEQ,ID,BOARDTYPE,TITLE,CONTENT,READCOUNT,COMMENTCOUNT,WDATE,DEL)
VALUES(BOARDSEQ.NEXTVAL, 'admin', 17, 'steak', '½ºÅ×ÀÌÅ©',0,0,'22/01/13', 0);
INSERT INTO BOARDALL(BOARDSEQ,ID,BOARDTYPE,TITLE,CONTENT,READCOUNT,COMMENTCOUNT,WDATE,DEL)
VALUES(BOARDSEQ.NEXTVAL, 'admin', 17, 'tteokbokki', '¶±ººÀÌ',0,0,'22/01/13', 0);
INSERT INTO BOARDALL(BOARDSEQ,ID,BOARDTYPE,TITLE,CONTENT,READCOUNT,COMMENTCOUNT,WDATE,DEL)
VALUES(BOARDSEQ.NEXTVAL, 'admin', 17, 'chicken', 'Ä¡Å²',0,0,'22/01/13', 0);
INSERT INTO BOARDALL(BOARDSEQ,ID,BOARDTYPE,TITLE,CONTENT,READCOUNT,COMMENTCOUNT,WDATE,DEL)
VALUES(BOARDSEQ.NEXTVAL, 'admin', 17, 'gookbab', '±¹¹ä',0,0,'22/01/13', 0);
INSERT INTO BOARDALL(BOARDSEQ,ID,BOARDTYPE,TITLE,CONTENT,READCOUNT,COMMENTCOUNT,WDATE,DEL)
VALUES(BOARDSEQ.NEXTVAL, 'admin', 17, 'pasta', 'ÆÄ½ºÅ¸',0,0,'22/01/13', 0);
INSERT INTO BOARDALL(BOARDSEQ,ID,BOARDTYPE,TITLE,CONTENT,READCOUNT,COMMENTCOUNT,WDATE,DEL)
VALUES(BOARDSEQ.NEXTVAL, 'admin', 17, 'pizza', 'ÇÇÀÚ',0,0,'22/01/13', 0);
INSERT INTO BOARDALL(BOARDSEQ,ID,BOARDTYPE,TITLE,CONTENT,READCOUNT,COMMENTCOUNT,WDATE,DEL)
VALUES(BOARDSEQ.NEXTVAL, 'admin', 17, 'sushi', '½º½Ã',0,0,'22/01/13', 0);

    
    commit;
    
    
    
SELECT
    * FROM BOARDALL;
    
DROP TABLE BOARDALL CASCADE CONSTRAINTS;
DROP SEQUENCE BOARDSEQ;
