CREATE TABLE COMMENTMBTI(
        COMMENTSEQ NUMBER(8) PRIMARY KEY,
        ALIAS VARCHAR2(200) NOT NULL, 
        BOARDSEQ NUMBER(8) NOT NULL,
        CONTENT VARCHAR2(4000) NOT NULL,
        WDATE DATE NOT NULL,
        DEL NUMBER(1) NOT NULL
);

--        CONSTRAINT FK_EMP_TEST FOREIGN KEY(DEPARTMENT_ID)
--        REFERENCES TB_DEPT(DEPARTMENT_ID)

CREATE SEQUENCE SEQ_COMMENT
START WITH 1 INCREMENT BY 1;

INSERT INTO COMMENTMBTI( COMMENTSEQ,ALIAS,BOARDSEQ,CONTENT,WDATE,DEL)
VALUES(SEQ_COMMENT.NEXTVAL, 'º’¥‘', 5, 'æ»≥Á«œººø‰', '22/01/12', 0);

    
commit;

SELECT *
FROM COMMENTMBTI;

SELECT COMMENTSEQ,ALIAS,BOARDSEQ,CONTENT,WDATE,DEL, count(*)
FROM COMMENTMBTI
WHERE BOARDSEQ=5
ORDER BY COMMENTSEQ DESC;