CREATE TABLE COMMENTMBTI(
        COMMENTSEQ NUMBER(8) PRIMARY KEY,
        ALIAS VARCHAR2(50) NOT NULL, 
        BOARDSEQ NUMBER(8) NOT NULL,
        REF NUMBER(8) NOT NULL,
        STEP NUMBER(8) NOT NULL,
        DEPTH NUMBER(8) NOT NULL,
        CONTENT VARCHAR2(4000) NOT NULL,
        WDATE DATE NOT NULL,
        DEL NUMBER(1) NOT NULL
);

CONSTRAINT FK_ALIAS FOREIGN KEY(ALIAS)
REFERENCES MEMBERMBTI(ALIAS);

CONSTRAINT FK_EMP_TEST FOREIGN KEY(DEPARTMENT_ID)
REFERENCES TB_DEPT(DEPARTMENT_ID);

--        CONSTRAINT FK_EMP_TEST FOREIGN KEY(DEPARTMENT_ID)
--        REFERENCES TB_DEPT(DEPARTMENT_ID)

CREATE SEQUENCE SEQ_COMMENT
START WITH 1 INCREMENT BY 1;

INSERT INTO COMMENTMBTI( COMMENTSEQ,ALIAS,REF,STEP,DEPTH,BOARDSEQ,CONTENT,WDATE,DEL)
VALUES(SEQ_COMMENT.NEXTVAL, '¼Õ´Ô', 0, 0, 0, 5, '¾È³çÇÏ¼¼¿ä', '22/01/12', 0);

    
commit;

SELECT *
FROM COMMENTMBTI;

SELECT COMMENTSEQ,ALIAS,BOARDSEQ,CONTENT,WDATE,DEL
FROM COMMENTMBTI
WHERE BOARDSEQ=5
ORDER BY COMMENTSEQ DESC;


SELECT *
FROM COMMENTMBTI
WHERE BOARDSEQ = (SELECT BOARDSEQ
    FROM WORLDCUP
    WHERE WORLDCUPNAME='gookbab')
ORDER BY REF asc, STEP desc;

Select max(step) from table
Where ref==ref and step>step and depth==depth+1;

SELECT BOARDSEQ
FROM WORLDCUP
WHERE WORLDCUPNAME='gookbab';

UPDATE WORLDCUP
SET
STEP = STEP + 1
WHERE STEP > (SELECT MAX(STEP) FROM TABLE WHERE REF == 40 AND STEP > 0 AND DEPTH == 0+1;

SELECT MAX(STEP) FROM COMMENTMBTI WHERE REF = 0 AND STEP > 2 AND DEPTH = 1+1;

SELECT COMMENTSEQ,ALIAS,REF, STEP, DEPTH,BOARDSEQ,CONTENT,WDATE,DEL
FROM COMMENTMBTI
WHERE boardseq=4
ORDER BY REF ASC, STEP ASC;