CREATE TABLE MEMBERMBTI(
    ID VARCHAR2(50) PRIMARY KEY,
    PWD VARCHAR2(100) NOT NULL,
    NAME VARCHAR2(50) NOT NULL,
    ALIAS VARCHAR2(50)UNIQUE,
    EMAIL VARCHAR2(50)UNIQUE,
    MBTI VARCHAR2(10) NOT NULL,
    AUTH NUMBER(1) NOT NULL,
    SALT VARCHAR(100) NOT NULL
);

DROP TABLE MEMBERMBTI;

COMMIT;
