-- 테이블 생성
CREATE TABLE WORLDCUP(
        WORLDCUPSEQ NUMBER(8) PRIMARY KEY,
        BOARDSEQ NUMBER(8) NOT NULL,
        TOPIC VARCHAR2(50) NOT NULL, 
        WORLDCUPNAME VARCHAR2(50) NOT NULL,
        CHOICECOUNT NUMBER(8) NOT NULL
    );

-- 시퀸스 생성
CREATE SEQUENCE SEQ_WORLDCUP
START WITH 1 INCREMENT BY 1;

-- 제약조건 추가 (Boardseq)
ALTER TABLE WORLDCUP ADD CONSTRAINT FK_WORLDCUP
      FOREIGN KEY (BOARDSEQ)
      REFERENCES BOARDALL(BOARDSEQ)
      ON DELETE CASCADE;

-- 행 추가        
INSERT INTO WORLDCUP(WORLDCUPSEQ, BOARDSEQ, TOPIC, WORLDCUPNAME, CHOICECOUNT)
VALUES(SEQ_WORLDCUP.NEXTVAL, 1, 'food', 'porkBelly', 0);

INSERT INTO WORLDCUP(WORLDCUPSEQ, BOARDSEQ, TOPIC, WORLDCUPNAME, CHOICECOUNT)
VALUES(SEQ_WORLDCUP.NEXTVAL, 21, 'food', 'steak', 0);

INSERT INTO WORLDCUP(WORLDCUPSEQ, BOARDSEQ, TOPIC, WORLDCUPNAME, CHOICECOUNT)
VALUES(SEQ_WORLDCUP.NEXTVAL, 22, 'food', 'tteokbokki', 0);

INSERT INTO WORLDCUP(WORLDCUPSEQ, BOARDSEQ, TOPIC, WORLDCUPNAME, CHOICECOUNT)
VALUES(SEQ_WORLDCUP.NEXTVAL, 23, 'food', 'chicken', 0);

INSERT INTO WORLDCUP(WORLDCUPSEQ, BOARDSEQ, TOPIC, WORLDCUPNAME, CHOICECOUNT)
VALUES(SEQ_WORLDCUP.NEXTVAL, 24, 'food', 'gookbab', 0);

INSERT INTO WORLDCUP(WORLDCUPSEQ, BOARDSEQ, TOPIC, WORLDCUPNAME, CHOICECOUNT)
VALUES(SEQ_WORLDCUP.NEXTVAL, 25, 'food', 'pasta', 0);

INSERT INTO WORLDCUP(WORLDCUPSEQ, BOARDSEQ, TOPIC, WORLDCUPNAME, CHOICECOUNT)
VALUES(SEQ_WORLDCUP.NEXTVAL, 26, 'food', 'pizza', 0);

INSERT INTO WORLDCUP(WORLDCUPSEQ, BOARDSEQ, TOPIC, WORLDCUPNAME, CHOICECOUNT)
VALUES(SEQ_WORLDCUP.NEXTVAL, 27, 'food', 'sushi', 0);
 
-- 커밋   
commit;

-- 해당 토픽의 월드컵 게시판들 가져오기
SELECT WORLDCUPSEQ, BOARDSEQ, TOPIC, WORLDCUPNAME, CHOICECOUNT
FROM WORLDCUP
WHERE TOPIC='food';

SELECT BOARDSEQ
FROM WORLDCUP
WHERE WORLDCUPNAME='pizza';